#服务端口
server:
  port: 8082


#服务注册中心配置
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8081/eureka/


#spring设置
spring:
 application:
   name: config-server
 cloud:
   config:
     server:
       git:
         uri: https://github.com/vvffeeffee/spring-cloud-repository.git
         searchPaths: CloudConfig-repo

